import os

Import('env')
env = env.Create("qttoolbox.colorbar", tools = ['default', 'qt'])

my_tools = env.Require(['PKG_QT'])

mydir=Dir('.')

def PKG_QTTOOLBOX_COLORBAR(env):
        env.Append(CPPPATH=[mydir,])
	env.Append(LIBPATH=[mydir,])
	env.Append(LIBS=['colorbar',])
	env.Append(QT_UICIMPLFLAGS=['-L', str(mydir)])
	env.Apply(my_tools)

Export('PKG_QTTOOLBOX_COLORBAR')

lib = env.SharedLibrary('colorbar', 
Split("""
 ColorBarBase.ui
 ColorBar.cpp
 ColorMap.cpp
 ColorBarPlugin.cpp
"""))

SConscript('Test/SConscript')
Default(lib)

env.Install(os.path.join(env['QTDIR'],'plugins','designer'), lib)