import os

Import('env')

SConscript('Test/SConscript')

# build colorbar shared library
colorbar = env.SharedLibrary(
   'colorbar',
   ['ColorBar.cpp','ColorBarPlugin.cpp','ColorMap.cpp']
)

Default(colorbar)

env.InstallLib(colorbar)



