import os

Import('pluginenv')

SConscript('Test/SConscript')

# build the custom widget and plugin

colorbar = pluginenv.SharedLibrary(
   'colorbar',
   ['ColorBar.cpp', 'ColorMap.cpp', 'ColorBarPlugin.cpp']
)

pluginenv.InstallLib(colorbar)

