import os

Import('qttbenv')

# uic colorbartest form
qttbenv.Uic4('ColorBarTest.ui')

# build colorbartest
colorbartest = qttbenv.Program(
   'colorbartest',
   ['main.cpp','ColorBarTest.cpp'],
   LIBS=['QtCore','QtGui','colorbar'],
   LIBPATH=['../','$QWTDIR/lib','$QTDIR/lib']
)

qttbenv.InstallBin(colorbartest)

Default(colorbartest)
