import os

env = Environment(tools=['default', 'qt4']) 
env.EnableQt4Modules(['QtCore','QtGui',])
env['QWTDIR'] = os.environ.get('QWTDIR', None)
env.AppendUnique(CPPPATH=['$QWTDIR/include', '..',])

# uic colorbartest form
env.Uic4('ColorBarTest.ui')

# build colorbartest
colorbartest = env.Program(
   'colorbartest',
   ['main.cpp','ColorBarTest.cpp'],
   LIBS=['QtCore','QtGui','colorbar'],
   LIBPATH=['../','$QWTDIR/lib','$QTDIR/lib']
)

Default(colorbartest)
