import os

Import('env')

SConscript('Test/SConscript')

# build ppi shared library
ppi = env.SharedLibrary(
   'ppi',
   ['PPI.cc','PPIPlugin.cpp','ScaledLabel.cpp'],
   LIBS=['colorbar','glut', 'QtOpenGL'],
   LIBPATH=['$QTDIR/lib','../ColorBar','$GLUTDIR/lib']
)

Default(ppi)

installdir = os.path.join('$QTDIR','plugins','designer')
env.Install(installdir, ppi)
env.Alias('install', installdir)



