import os

SConscript('Test/SConscript')

env = Environment(tools=['default', 'qt4'])
env['QWTDIR'] = os.environ.get('QWTDIR', None)
env.AppendUnique(CPPPATH=['$QWTDIR/include', '..', '$QTDIR/include/QtDesigner', '/usr/include/GL','../ColorBar'])
env.AppendUnique(QT4_MOCFROMHFLAGS=['-I', '$QTDIR/include/QtDesigner/'])
env.EnableQt4Modules(['QtCore','QtGui','QtOpenGL'])

# build ppi shared library
ppi = env.SharedLibrary(
   'ppi',
   ['PPI.cc','PPIPlugin.cpp','ScaledLabel.cpp'],
   LIBS=['colorbar','glut', 'QtOpenGL'],
   LIBPATH=['$QTDIR/lib','../ColorBar']
)

Default(ppi)

installdir = os.path.join('$QTDIR','plugins','designer')
env.Install(installdir, ppi)
env.Alias('install', installdir)



