import os

Import('pluginenv')

pluginenv.AppendUnique(CPPPATH=['../ColorBar'])

SConscript('Test/SConscript')

# build ppi shared library
ppi = pluginenv.SharedLibrary(
   'ppi',
   ['PPI.cc','PPIPlugin.cpp','ScaledLabel.cpp'],
   LIBS=['colorbar','glut', 'QtOpenGL'],
   LIBPATH=['$QTDIR/lib','../ColorBar','$GLUTDIR/lib']
)

Default(ppi)

pluginenv.InstallLib(ppi)


