import os

Import('pluginenv')

SConscript('Test/SConscript')

# uic scopeplot form
pluginenv.Uic4('ScopePlot.ui')

# build knob shared library
scopeplot = pluginenv.SharedLibrary(
   'scopeplot',
   ['ScopePlot.cpp','ScopePlotPlugin.cpp','ScrollBar.cpp','ScrollZoomer.cpp'],
   LIBS=['qwt',],
   LIBPATH=['$QWTDIR/lib',]
)

Default(scopeplot)

pluginenv.InstallLib(scopeplot)



