import os

Import('env')

SConscript('Test/SConscript')

# uic scopeplot form
env.Uic4('ScopePlot.ui')

# build knob shared library
scopeplot = env.SharedLibrary(
   'scopeplot',
   ['ScopePlot.cpp','ScopePlotPlugin.cpp','ScrollBar.cpp','ScrollZoomer.cpp'],
   LIBS=['qwt',],
   LIBPATH=['$QWTDIR/lib',]
)

Default(scopeplot)

env.InstallLib(scopeplot)



