import os

env = Environment(tools=['default', 'qt4']) 
env.EnableQt4Modules(['QtCore','QtGui',])
env['QWTDIR'] = os.environ.get('QWTDIR', None)
env.AppendUnique(CPPPATH=['$QWTDIR/include', '..',])

# uic knobtest form
env.Uic4('TwoKnobsTest.ui')

# build knobtest
twoknobstest = env.Program(
   'twoknobstest',
   'main.cpp',
   LIBS=['QtCore','QtGui','twoknobs','qwt'],
   LIBPATH=['../','$QWTDIR/lib','$QTDIR/lib']
)

Default(twoknobstest)
