import os

Import('qttbenv')

# uic knobtest form
qttbenv.Uic4('TwoKnobsTest.ui')

# build knobtest
twoknobstest = qttbenv.Program(
   'twoknobstest',
   'main.cpp',
   LIBS=['QtCore','QtGui','twoknobs','qwt'],
   LIBPATH=['../','$QWTDIR/lib','$QTDIR/lib']
)

qttbenv.InstallBin(twoknobstest)

Default(twoknobstest)
