
Import('env')
env = env.Create("qttoolbox.twoknobstest", tools = ['default', 'qt'])
env.Require(Split("""
PKG_QTTOOLBOX_TWOKNOBS
"""))

p = env.Program('twoknobstest',Split("""
  TwoKnobsTest.ui
  main.cpp
  """) )

Default(p)
