import os

Import('pluginenv')

SConscript('Test/SConscript')

# uic knob form
pluginenv.Uic4('Knob.ui')

# build knob shared library
knob = pluginenv.SharedLibrary(
   'knob',
   ['Knob.cpp','KnobPlugin.cpp',],
   LIBS=['qwt',],
   LIBPATH=['$QWTDIR/lib',]
)

pluginenv.InstallLib(knob)

Default(knob)


