import os

Import('env')

SConscript('Test/SConscript')

# uic knob form
env.Uic4('Knob.ui')

# build knob shared library
knob = env.SharedLibrary(
   'knob',
   ['Knob.cpp','KnobPlugin.cpp',],
   LIBS=['qwt',],
   LIBPATH=['$QWTDIR/lib',]
)

Default(knob)

env.InstallLib(knob)



