import os

Import('env')

SConscript('Test/SConscript')

# uic knob form
env.Uic4('TwoKnobs.ui')

# build knob shared library
twoknobs = env.SharedLibrary(
   'twoknobs',
   ['TwoKnobs.cpp','TwoKnobsPlugin.cpp',],
   LIBS=['qwt',],
   LIBPATH=['$QWTDIR/lib',]
)

Default(twoknobs)

installdir = os.path.join('$QTDIR','plugins','designer')
env.Install(installdir, twoknobs)
env.Alias('install', installdir)

