import os

Import('pluginenv')

SConscript('Test/SConscript')

# uic knob form
pluginenv.Uic4('TwoKnobs.ui')

# build knob shared library
twoknobs = pluginenv.SharedLibrary(
   'twoknobs',
   ['TwoKnobs.cpp','TwoKnobsPlugin.cpp',],
   LIBS=['qwt',],
   LIBPATH=['$QWTDIR/lib',]
)

Default(twoknobs)

pluginenv.InstallLib(twoknobs)
