tools = ['qtt_common', 'qtt_scopeplot']
env = Environment(tools = ['default'] + tools)

# uic ScopePlotTest form
env.Uic4('ScopePlotTest.ui')

# build scopeplottest
sources = Split("""
main.cpp
ScopePlotTest.cpp
ScopePoke.cpp
""")
scopeplottest = env.Program('scopeplottest', sources)

env.InstallBin(scopeplottest)

Default(scopeplottest)
