import os

env = Environment(tools=['default', 'qt4']) 
env.EnableQt4Modules(['QtCore','QtGui',])
env['QWTDIR'] = os.environ.get('QWTDIR', None)
env.AppendUnique(CPPPATH=['$QWTDIR/include', '..',])

# uic ScopePlotTest form
env.Uic4('ScopePlotTest.ui')

# build scopeplottest
scopeplottest = env.Program(
   'scopeplottest',
   ['main.cpp','ScopePlotTest.cpp','ScopePoke.cpp'],
   LIBS=['QtCore','QtGui','scopeplot','qwt'],
   LIBPATH=['../','$QWTDIR/lib','$QTDIR/lib']
)

Default(scopeplottest)
