#
# This SConstruct file is provided so that bscan
# can either be built from this directory, or the
# SConscript can be called as a subdirectory of
# other scons projects.
#    
SConscript('SConscript')
