env = Environment(tools = ['default', 'qtt_common', 'qtt_knob'])

# uic knobtest form
env.Uic('KnobTest.ui')

# build knobtest
knobtest = env.Program('knobtest', ['main.cpp'])
knobtest_install = env.InstallBin(knobtest)

Default(knobtest)
