import os

Import('qttbenv')

# uic knobtest form
qttbenv.Uic4('KnobTest.ui')

# build knobtest
knobtest = qttbenv.Program(
   'knobtest',
   'main.cpp',
   LIBS=['QtCore','QtGui','knob','qwt'],
   LIBPATH=['../','$QWTDIR/lib','$QTDIR/lib']
)

qttbenv.InstallBin(knobtest)