import os

env = Environment(tools=['default', 'qt4']) 
env.EnableQt4Modules(['QtCore','QtGui','QtOpenGL'])
env['QWTDIR'] = os.environ.get('QWTDIR', None)
env.AppendUnique(CPPPATH=['$QWTDIR/include', '..','../../ColorBar'])

# uic ppitest form
env.Uic4('PPITest.ui')

# build ppitest
ppitest = env.Program(
   'ppitest',
   ['main.cpp','PPITest.cc'],
   LIBS=['QtCore','QtGui','ppi','colorbar'],
   LIBPATH=['../','../../ColorBar','$QWTDIR/lib','$QTDIR/lib']
)

Default(ppitest)
