import os

Import('env')

# uic ppitest form
env.Uic4('PPITest.ui')

# build ppitest
ppitest = env.Program(
   'ppitest',
   ['main.cpp','PPITest.cc'],
   LIBS=['QtCore','QtGui','ppi','colorbar'],
   LIBPATH=['../','../../ColorBar','$QWTDIR/lib','$QTDIR/lib']
)

Default(ppitest)
